### ISSUE TITLE
Release 0.2.2 version issue

### ISSUE THREAD

**Issue by aliesbelik** [ChillFish8/rewrk#13]
Looks like there is a confusion with the [last release](https://github.com/ChillFish8/rewrk/releases/tag/0.2.2): specified as 0.2.2 in release vs. 0.1.2 displayed by binary itself:

![rewrk_version_issue](https://user-images.githubusercontent.com/1752374/129200023-a0b330d0-bea5-43f3-adaf-0527f7553f2c.png)

**Comment by programatik29** [comment]
Thanks for pointing that out.

**Comment by ChillFish8** [comment]
Fix has been merged into v0.3.x I recommend building from source rather than the releases as they're pretty old, I need to set up a CI for that, but yet another thing on the TODO list.

**Comment by aliesbelik** [comment]
Thank you for quick reaction.
Ok, will try to build from source, although it seems be a good option to have actual ready-to-use binaries for future release.
