### ISSUE TITLE
number of threads problem

### ISSUE THREAD

**Issue by ecafkoob** [ChillFish8/rewrk#18]
<img width="744" alt="image" src="https://user-images.githubusercontent.com/12779980/132600545-5e1f189b-e804-4fd5-9048-8aaa4eae322a.png">

I would like to know why rewrk opened so many threads.

**Comment by ChillFish8** [comment]
Thats a good question, im not sure why your process manager is spawning that many, im away for a couple days right now so wont be able to fully investigate until Sunday.

**Comment by ChillFish8** [comment]
Are you able to observe behavour when using 127.0.0.1 instead of localhost?

**Comment by ChillFish8** [comment]
If you're able to verify the the mentioned pr solves this issue please let me know 🙂

**Comment by ecafkoob** [comment]
thread number is ok.good job  : )
