### ISSUE TITLE
Data Transfer only reads body size

### ISSUE THREAD

**Issue by ChillFish8** [ChillFish8/rewrk#3]
This can be a potentially big issue for people and likely miss-leading as the current system does not support messuring the headers aswell, not sure what a possible soloution is if hyper doesnt give a direct interface for this.

**Comment by programatik29** [comment]
It is possible. In fact [I managed to do it](https://github.com/programatik29/rewrk/tree/custom-tcp-stream). It requires my low level **conn** api [pull request](https://github.com/ChillFish8/rewrk/pull/5) to be merged first.

**Comment by ChillFish8** [comment]
low level conn api has been merged so should be good for counting bytes provided its not to wild

**Comment by ChillFish8** [comment]
fixed from recent PRs
