### ISSUE TITLE
rewrk fails to process arguments when used via some external program 

### ISSUE THREAD

**Issue by ishtms** [ChillFish8/rewrk#30]
Hi, I am currently building a [framework benchmark tool](https://github.com/ishtms/rust-framework-benchmarks) using rust, and just switched from using wrk to rewrk. Loving it so far as it doesn't has inconsistencies like wrk.

There are some issues with clap when it comes to parsing through another program, for example rust's own `std::process::Command` utility. I am also submitting a PR to get rid all these issues.

## Problem

Here's a demo code that my benchmark program is using (using absolute path just to debug it further)

![code](https://user-images.githubusercontent.com/30657558/180651667-7451e81e-5f8c-4046-b20d-21a16ee272e1.png)

The exact same arguments seem to work okay with wrk, and any other programs. However, because of this clap issue, rewrk expects us to either specify arguments using `t=2` `threads=2` or `t2`.

## Solution
**Threads**
```rs
// It's trying to parse a `usize` when the value is like ` 3` - with a space, which fails
// clap doesn't removes that space
let threads: usize = match args.value_of("threads").unwrap_or("1").parse()
```

**connections**
```rs
// Same issue as above
let conns: usize = match args.value_of("connections").unwrap_or("1").parse()
```

**rounds**
```rs
// Same issue as above
let rounds: usize = args  .value_of("rounds") .unwrap_or("1").parse()
```

**host/url**
```rs
// again the `uri` fails to parse since it has a space ` http://localhost:3000`
let user_input = UserInput::new(bench_type, uri_string).await?;
```

There's a quick fix - trimming values and that will do it for all the use cases. I'll be submitting a PR that fixes all these.

**Comment by ChillFish8** [comment]
Sounds reasonable to me, probably worth upgrading to clap 3 and using the derived version of the options instead in the future 👍
